### ISSUE TITLE
The Adobe Flash plugin is not installed

### ISSUE THREAD

**Issue by mercurytrans** [phpvirtualbox/phpvirtualbox#174] opened 2019-07-06 18:45 UTC
Hi,
Just installed phpvirtualbox on Ubuntu Server 18.04.

Everything works fine, except the phpvirtualbox's console.

Clicking on "Console" button, the error message "The Adobe Flash plugin is not installed" shows up.

I'm using Google Chrome browser (ver. 75.0 last update on July 5 2019).

Thanks for any help.

Best regards

**Comment by dreyTee** [comment] 2019-07-30 02:55
same issue (Version 75.0.3770.142 (Official Build) (64-bit))
anywhere else flash works (chrome://components/ shows: Adobe Flash Player - Version: 32.0.0.223 Status - Up-to-date)

**Comment by ajacocks** [comment] 2019-08-22 18:58
I'm seeing the same thing, using Chrome and Firefox

**Comment by chotaire** [comment] 2019-09-06 07:33
Using Chrome, after loading the phpVirtualBox site, you need to click on the icon infront of the URL, and select "Allow" in the Flash dropdown menu. Once done, click the "Reload" button in the popup bar to reload the phpvirtualbox page. Now Flash works on phpvirtualbox.

This needs to be done each time you restart your browser.

**Comment by chotaire** [comment] 2019-09-07 10:19
@mercurytrans Please verify my suggestion works and if that's the case please close this issue. Thank you.

**Closed** 2019-09-07 11:05 UTC

**Comment by vlotho** [comment] 2019-10-13 22:51
hi,
I have the same problem and even after having authorized flash, the same message is displayed.

**Comment by trasherdk** [comment] 2019-10-14 08:04
I was under the impression that all major browsers has stopped supporting Adobe Flash for security reasons. I they didn't already stopped support, they will soonish.

[Flash to HTML5 — What the End of Life for Flash Will Mean for You](https://www.focuseduvation.com/flash-html5-end-life-flash-will-mean/)

**Comment by h6w** [comment] 2019-10-14 23:55
My Chrome warns that it will happen in 2020.  It's not the easiest thing to replace but we are working on it.

**Comment by mikysal78** [comment] 2020-02-23 00:11
i have debian buster and on chromium don't work!

**Comment by afteroot** [comment] 2021-01-19 13:28
The same problem debian 9, 10

**Comment by blackcrack** [comment] 2021-01-19 13:47
hmmmm.. maybe updating to html5 + webgl ?
i have to less experience for that.. but maybe anyone else could make it..

**Comment by afteroot** [comment] 2021-01-19 13:49
For now im using redmina, just set hostname of Vbox ans set port for RDP connection.
Works well

**Comment by h6w** [comment] 2021-01-20 08:38
> hmmmm.. maybe updating to html5 + webgl ?
> i have to less experience for that.. but maybe anyone else could make it..

Unfortunately no.  The real problem (as mentioned in the official bug) is that Adobe Flash was the only plugin allowed to make connections to non-web port numbers.  HTML5 does not allow it.  Without this, we can't implement any RDP or VNC client without a server relay (e.g. WebSocket to RDP like Guacamole et al does).  Since PHP is stateless we can't implement a stated relay at all within the expected design, let alone one that would stay open long enough to be useable.  Unless someone miraculously comes up with a way to do direct connections to RDP, or we migrate from PHP to NodeJS Server (which limits the install base and starts to conflict with other projects) it makes more sense to say that connections to VMs should be made directly using an RDP/VNC client like Remmina and instead provide a rdp:// or vnc:// link to the VM.

**Comment by justiceserv** [comment] 2021-02-04 08:54
Okay, now what? Adobe Flash is EOL and I can't do a thing.

**Comment by chotaire** [comment] 2021-02-04 09:17
@justiceserv You can do everything. All you need is an RDP client, just like the Flash app was an RDP client. It only gets a little tricky with mstsc if you have manually enabled RDP encryption/authentication using the CLI. But even that works.

**Comment by chotaire** [comment] 2021-02-04 09:26
To anyone else who's gonna complain: Ruffle supporting ActionScript 3 (most notably execution of AVM2 bytecode and EventListeners) to be able to run the existing Oracle Flash applet in phpVirtualBox is most likely going to happen sooner (I guess 9-12 months) than someone implementing a proper non-flash RDP applet into this php project. That Flash applet was extremely buggy anyway, so please: Get used to an RDP client.

**Comment by justiceserv** [comment] 2021-02-04 10:22
> @justiceserv You can do everything. All you need is an RDP client, just like the Flash app was an RDP client. It only gets a little tricky with mstsc if you have manually enabled RDP encryption/authentication using the CLI. But even that works.

I did not setted up RDP encryption or authentication using CLI. 
Also, 
![image](https://user-images.githubusercontent.com/51410592/106879177-26a59e00-671e-11eb-9f26-960c2ecfdd19.png)
I tried to connect to it, and it failed to connect to through microsoft remote desktop client.

**Comment by chotaire** [comment] 2021-02-04 11:02
Yes it failed because you are trying to connect to localhost. That is not an issue but a malconfiguration. Edit config.php and change the following to a reachable IP used by your VirtualBox host.

```
// Host / ip to use for console connections
var $consoleHost = '127.0.0.1';

```

**Comment by justiceserv** [comment] 2021-02-04 11:07
> Yes it failed because you are trying to connect to localhost. That is not an issue but a malconfiguration. Edit config.php and change the following to a reachable IP used by your VirtualBox host.
> 
> ```
> // Host / ip to use for console connections
> var $consoleHost = '127.0.0.1';
> ```

![image](https://user-images.githubusercontent.com/51410592/106884355-8ef77e00-6724-11eb-9341-50375011db16.png)
I did change it before.

**Comment by chotaire** [comment] 2021-02-04 11:14
Then you most likely are having an issue that is not related at all to phpVirtualBox, yet alone VirtualBox. Check firewall rules, selinux, listeners on the host, and if the VM is actually running when you are trying to connect, etc.. In any case this is a support issue that doesn't belong into a closed bug ticket. Good luck finding the cause.

**Comment by trasherdk** [comment] 2021-02-04 11:45
Easy fix: `vrdeaddress = $_SERVER['SERVER_ADDR'];`

**Comment by h6w** [comment] 2021-02-04 23:09
> ...Ruffle supporting ActionScript 3 (most notably execution of AVM2 bytecode and EventListeners) to be able to run the existing Oracle Flash applet in phpVirtualBox is most likely going to happen sooner (I guess 9-12 months) than someone implementing a proper non-flash RDP applet into this php project. That Flash RDP applet by Oracle was extremely buggy anyway, so please: Get used to an RDP client.

Actually, the bigger problem is that browsers now block all ports except for a small subset (which is getting smaller after Chrome's announcement this past week) and RDP is not in that list.  So anything that's native to the browser is never going to work because of the browser security model.  We made a few attempts to get a kind of stateless port forwarding through websockets but RDP didn't like it at all.

**Comment by justiceserv** [comment] 2021-02-05 04:30
> Easy fix: `vrdeaddress = $_SERVER['SERVER_ADDR'];`

That caused php syntax error, but thanks. 
I have to check whats wrong :p

**Comment by trasherdk** [comment] 2021-02-08 04:14
@justiceserv 

I've added, to the end of `config.php` :

```php
/* END SETTINGS  */

  public function phpVBoxConfig() {
    if($this->authLib == 'VBoxAuthSimple') {
      session_start();
      $this->username = $this->getUsername();
      $this->password = $this->getPassword();
    }
    if ($this->vrdeaddress == '' || $this->vrdeaddress == '127.0.0.1' ) {
      $this->vrdeaddress = $_SERVER['SERVER_ADDR'];
    }
  }

  public function getUsername() {
    return $_SESSION['user'];
  }

  public function getPassword() {
    return $_SESSION['password'];
  }

}  /** <-- end of class phpVBoxConfig { **/
```

**Comment by blackcrack** [comment] 2021-02-08 08:14
@trasherdk could you maybe add this as patch direct in the PHP-VBox-config / config.php-example 
with a good description ?
https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/config.php-example
best
