### ISSUE TITLE
It seems that the Flash Remote Desktop client should be replaced

### ISSUE THREAD

**Issue by myqmdx** [phpvirtualbox/phpvirtualbox#128] opened 2018-05-23 08:07 UTC
Hello, some browsers no longer support Flash, and Adobe will officially stop updating Flash in 2020 (https://theblog.adobe.com/adobe-flash-update/). I think phpvirtualbox should be replaced the current Flash Remote Desktop client.

**Comment by h6w** [comment] 2018-06-04 03:35
This is a duplicate of #111

**Closed by h6w** 2018-06-04 03:35 UTC
