### ISSUE TITLE
Option to view the virtual machine in HTML 5

### ISSUE THREAD

**Issue by GoNotCougsWA** [phpvirtualbox/phpvirtualbox#112] opened 2018-03-17 22:16 UTC
I would really like if you guys add html 5 Option to view/move the virtual machine. I know it's possible.

**Comment by lapo-luchini** [comment] 2018-03-27 11:06
If by "move" you mean change the order (or grouping) in the list of machines, it's already possibile.

**Comment by GoNotCougsWA** [comment] 2018-03-27 22:52
What I am talking about is to view the virtual machine in HTML 5 and also, be able to control the virtual machine in HTML 5.

**Comment by h6w** [comment] 2018-03-27 22:53
I think this may be a duplicate of issue #111

**Comment by GoNotCougsWA** [comment] 2018-03-28 00:51
Your right! I didn't know know it was in phpvirtualbox already. lol.

**Closed** 2018-03-28 01:14 UTC
