### ISSUE TITLE
create_function is deprecated in PHP 7.2

### ISSUE THREAD

**Issue by Fightbackman** [phpvirtualbox/phpvirtualbox#101] opened 2018-03-01 21:05 UTC
I just installed phpvirtualbox on my arch linux box and encountered the following error when clicking on my first created machine:
```

Deprecated:  Function create_function() is deprecated in /usr/share/webapps/phpvirtualbox/endpoints/lib/vboxconnector.php on line 3947

Deprecated:  Function create_function() is deprecated in /usr/share/webapps/phpvirtualbox/endpoints/lib/vboxconnector.php on line 3947

Deprecated:  Function create_function() is deprecated in /usr/share/webapps/phpvirtualbox/endpoints/lib/vboxconnector.php on line 3947

Deprecated:  Function create_function() is deprecated in /usr/share/webapps/phpvirtualbox/endpoints/lib/vboxconnector.php on line 3947

Deprecated:  Function create_function() is deprecated in /usr/share/webapps/phpvirtualbox/endpoints/lib/vboxconnector.php on line 4503

Deprecated:  Function create_function() is deprecated in /usr/share/webapps/phpvirtualbox/endpoints/lib/vboxconnector.php on line 4503
{"data":{"responseData":{"name":"vmName","description":"","groups":["\/"],"id":"747c14ba-c1e2-4d83-9cb0-b90fb4829333","autostopType":"","autostartEnabled":false,"autostartDelay":"0","settingsFilePath":"\/root\/VirtualBox VMs\/vmName\/vmName","paravirtProvider":"Default","OSTypeId":"Debian_64","OSTypeDesc":"Debian (64-bit)","CPUCount":1,"HPETEnabled":false,"memorySize":1024,"VRAMSize":16,"pointingHIDType":"PS2Mouse","keyboardHIDType":"PS2Keyboard","accelerate3DEnabled":false,"accelerate2DVideoEnabled":false,"BIOSSettings":{"ACPIEnabled":true,"IOAPICEnabled":true,"timeOffset":0},"firmwareType":"BIOS","snapshotFolder":"\/root\/VirtualBox VMs\/vmName\/Snapshots","monitorCount":1,"pageFusionEnabled":false,"VRDEServer":{"enabled":false,"ports":"3389","netAddress":"","VNCPassword":"","authType":"Null","authTimeout":5000,"allowMultiConnection":false,"VRDEExtPack":""},"audioAdapter":{"enabled":true,"audioController":"AC97","audioDriver":"ALSA"},"RTCUseUTC":true,"EffectiveParavirtProvider":"KVM","HWVirtExProperties":{"Enabled":true,"NestedPaging":true,"LargePages":false,"UnrestrictedExecution":true,"VPID":true},"CpuProperties":{"PAE":false},"bootOrder":["Floppy","DVD","HardDisk"],"chipsetType":"PIIX3","GUI":{"FirstRun":"yes"},"customIcon":"","disableHostTimeSync":0,"CPUExecutionCap":100,"networkAdapters":[{"adapterType":"I82540EM","slot":0,"enabled":true,"MACAddress":"080027A3687D","attachmentType":"NAT","genericDriver":"","hostOnlyInterface":"","bridgedInterface":"","properties":"","internalNetwork":"","NATNetwork":"","promiscModePolicy":"Deny","VDENetwork":"","cableConnected":true,"NATEngine":{"aliasMode":0,"DNSPassDomain":true,"DNSProxy":false,"DNSUseHostResolver":false,"hostIP":""},"lineSpeed":0,"redirects":[]},{"adapterType":"I82540EM","slot":1,"enabled":false,"MACAddress":"","attachmentType":"Null","genericDriver":"","hostOnlyInterface":"","bridgedInterface":"","properties":"","internalNetwork":"","NATNetwork":"","promiscModePolicy":"Deny","VDENetwork":"","cableConnected":true,"NATEngine":{"aliasMode":0,"DNSPassDomain":0,"DNSProxy":0,"DNSUseHostResolver":0,"hostIP":""},"lineSpeed":0,"redirects":[]},{"adapterType":"I82540EM","slot":2,"enabled":false,"MACAddress":"","attachmentType":"Null","genericDriver":"","hostOnlyInterface":"","bridgedInterface":"","properties":"","internalNetwork":"","NATNetwork":"","promiscModePolicy":"Deny","VDENetwork":"","cableConnected":true,"NATEngine":{"aliasMode":0,"DNSPassDomain":0,"DNSProxy":0,"DNSUseHostResolver":0,"hostIP":""},"lineSpeed":0,"redirects":[]},{"adapterType":"I82540EM","slot":3,"enabled":false,"MACAddress":"","attachmentType":"Null","genericDriver":"","hostOnlyInterface":"","bridgedInterface":"","properties":"","internalNetwork":"","NATNetwork":"","promiscModePolicy":"Deny","VDENetwork":"","cableConnected":true,"NATEngine":{"aliasMode":0,"DNSPassDomain":0,"DNSProxy":0,"DNSUseHostResolver":0,"hostIP":""},"lineSpeed":0,"redirects":[]}],"storageControllers":[{"name":"SATA","maxDevicesPerPortCount":1,"useHostIOCache":false,"minPortCount":1,"maxPortCount":30,"portCount":1,"bus":"SATA","controllerType":"IntelAhci","mediumAttachments":[{"medium":{"id":"1a75cc8d-4362-4b5d-a4eb-69cf9bc13d39"},"controller":"SATA","port":0,"device":0,"type":"HardDisk","passthrough":false,"temporaryEject":false,"nonRotational":false,"hotPluggable":false,"ignoreFlush":1}]},{"name":"IDE","maxDevicesPerPortCount":2,"useHostIOCache":true,"minPortCount":2,"maxPortCount":2,"portCount":2,"bus":"IDE","controllerType":"PIIX4","mediumAttachments":[{"medium":null,"controller":"IDE","port":1,"device":0,"type":"DVD","passthrough":false,"temporaryEject":false,"nonRotational":false,"hotPluggable":false,"ignoreFlush":""}]}],"serialPorts":[{"slot":0,"enabled":false,"IOBase":"0x3F8","IRQ":4,"hostMode":"Disconnected","server":false,"path":""},{"slot":1,"enabled":false,"IOBase":"0x2F8","IRQ":3,"hostMode":"Disconnected","server":false,"path":""},{"slot":2,"enabled":false,"IOBase":"0x3E8","IRQ":4,"hostMode":"Disconnected","server":false,"path":""},{"slot":3,"enabled":false,"IOBase":"0x2E8","IRQ":3,"hostMode":"Disconnected","server":false,"path":""}],"parallelPorts":[],"sharedFolders":[],"USBControllers":[],"USBDeviceFilters":[],"currentSnapshot":null,"snapshotCount":0,"accessible":1},"success":true,"key":"53474945cfd7ac0bf8114767c209c2a6"},"errors":[],"persist":[],"messages":[]}
```

As [here](https://secure.php.net/manual/en/function.create-function.php) described this fuction has been deprecated with PHP version 7.2

Is there any possibilty to fix this in the near future?

**Comment by tom077** [comment] 2018-03-03 18:37
Hi,

The current 5.2-0 release is supposed to fix PHP 7.2 compatibility (see #98).

Did you install the phpvirtualbox archlinux package? It's based on an old release (5.2-0-rc1).
I just report the archlinux package as outdated.

So you have to wait for the archlinux maintainer to update the package or you can manually install the github tarball available here : https://github.com/phpvirtualbox/phpvirtualbox/archive/5.2-0.tar.gz

**Comment by tom077** [comment] 2018-03-06 10:44
A new phpvirtualbox 5.2_0-1 package is now available for Archlinux.

**Comment by h6w** [comment] 2018-03-07 03:12
I have searched through all the current code and cannot find create_function being used anymore.  Closing as not a bug.

**Closed by h6w** 2018-03-07 03:12 UTC
Labels: invalid
