### ISSUE TITLE
Replace Oracle RDP Web Control (Adobe Flash)

### ISSUE THREAD

**Issue by chotaire** [phpvirtualbox/phpvirtualbox#190] opened 2019-09-07 14:35 UTC
In July 2017, Adobe announced that it would end support for Flash Player at the end of 2020, and continued to encourage the use of open HTML5 standards in place of Flash. The announcement was coordinated with Apple, Facebook, Google, Microsoft, and Mozilla. All major browsers have already begun phasing out Flash. At the time of this writing it is already becoming a major hurdle for users to even use the Oracle RDP Web Control provided by phpVirtualBox. 

It is of utmost importance that this flash applet is replaced with a HTML5 (or similar open technology) version as soon as possible, before major browsers make it entirely impossible to use VM consoles with phpVirtualBox. Let's not see this project die alongside Adobe Flash.

Information about the Adobe Flash road to death:
https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html
https://webkit.org/blog/7839/adobe-announces-flash-distribution-and-updates-to-end/
https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/
https://blogs.windows.com/msedgedev/2017/07/25/flash-on-windows-timeline/
https://developer.mozilla.org/en-US/docs/Plugins/Roadmap

Here are a few HTML5 rdp clients I have found which may or may not be of interest:
http://guacamole.apache.org/
https://cedrozor.github.io/myrtille/
https://github.com/FreeRDP/FreeRDP-WebConnect
https://github.com/gonewbee/webRDP
https://github.com/wallix/redemption
https://www.remotespark.com/html5.html (free personal license)

Also please note there is a VNC extension pack for source code versions of VirtualBox, along with instructions on how to use it: https://www.virtualbox.org/manual/ch09.html#otherextpacks - I assume that this is not remotely the same quality (e.g. keyboard input handling) than VRDP though.

Also check out https://github.com/phpvirtualbox/phpvirtualbox/issues/33 where I just uploaded the original zipfile that incorporates SparkGateway into VirtualBox for VNC connections.

**Comment by chotaire** [comment] 2019-09-08 14:39
As a note, if using RDP encryption (Negotiated) and authentication (in my test this was external authentication with VBoxSimple) -  something that everyone should be doing if they are not the single user on a network - then a connection using the Microsoft RDP client to a VirtualBox Console will be disconnected using the generated .rdp files. This also won't work when opening mstsc.exe and directly connecting to the IP:port. The trick is to check the checkbox for credentials to be saved. This is currently the only way to be able to connect using mstsc. Tested with Windows 10 1903.

**Comment by h6w** [comment] 2019-09-12 04:07
Duplicate of Issue #111

**Closed by h6w** 2019-09-12 04:07 UTC
