### ISSUE TITLE
Flash replacement?

### ISSUE THREAD

**Issue by jmar83** [phpvirtualbox/phpvirtualbox#228] opened 2020-03-01 16:49 UTC
Hi there

What do you think about a flash replacement, i think there are some HTML5 technologies to replace flash. (Proxmox also seems to be able to display the virtual machine screen in its web-gui, without any flash technologies...)

Are there some plans to do that?

Thank you for your feedbacks.

Best regards,
Jan

**Comment by h6w** [comment] 2020-03-02 01:13
Duplicate of #111

**Closed by h6w** 2020-03-02 01:13 UTC
