### ISSUE TITLE
snapshot issue with phpvirtualbox-6

### ISSUE THREAD

**Issue by olivier108** [phpvirtualbox/phpvirtualbox#177] opened 2019-07-19 09:27 UTC
I am using phpvirtualbox-6 adaptation for virtualbox6 (6.0.8r130520)
https://github.com/pasha1st/phpvirtualbox-6/

It's working fine except for the snapshots : when I try to take a snapshot, the vm is paused then resumed but no snapshot happens (snapshots work fine on the command line)

Any hint on how to debug the issue?

Below the vm log 

_00:25:10.849817 Changing the VM state from 'RUNNING' to 'SUSPENDING'
00:25:10.850951 AIOMgr: Endpoint for file '/home/vbox/VirtualBox VMs/BioSQL/CentOS7 SQL.vdi' (flags 000c0781) created successfully
00:25:10.864976 AIOMgr: Endpoint for file '/home/vbox/VirtualBox VMs/BioSQL/CentOS7 SQL-DATA.vdi' (flags 000c0781) created successfully
00:25:10.910568 PDMR3Suspend: 60 683 860 ns run time
00:25:10.910585 Changing the VM state from 'SUSPENDING' to 'SUSPENDED'
00:25:10.910596 Console: Machine state changed to 'Paused'
00:25:11.271861 Changing the VM state from 'SUSPENDED' to 'RESUMING'
00:25:11.272057 AIOMgr: Endpoint for file '/home/vbox/VirtualBox VMs/BioSQL/CentOS7 SQL.vdi' (flags 000c0723) created successfully
00:25:11.272983 AIOMgr: Endpoint for file '/home/vbox/VirtualBox VMs/BioSQL/CentOS7 SQL-DATA.vdi' (flags 000c0723) created successfully
00:25:11.274171 Changing the VM state from 'RESUMING' to 'RUNNING'
00:25:11.274188 Console: Machine state changed to 'Running'
00:25:52.055090 AIOMgr: Flush failed with VERR_INVALID_PARAMETER, disabling async flushes
00:25:54.712085 AIOMgr: Flush failed with VERR_INVALID_PARAMETER, disabling async flushes_

Thanks for your help

**Comment by chotaire** [comment] 2019-09-07 13:18
This doesn't really belong here, as this addresses a phpvirtualbox fork. However, @pasha1st can you please look into this?

**Comment by chotaire** [comment] 2019-09-07 13:19
Someone please also test if this issue is also present in https://github.com/phpvirtualbox/phpvirtualbox/pull/186 - thank you.

**Comment by chotaire** [comment] 2019-09-07 14:20
This doesn't belong here, this addresses an issue present in a phpvirtualbox fork by @pasha1st which is not supported by the phpVirtualBox team. Any way, I have looked into this and found the problem. That fork uses vboxServiceWrappers.php from an SDK provided by Oracle which breaks the snapshot functionality. If you revert to the vboxServiceWrappers.php provided by phpVirtualBox (which includes a vast number of fixes by the team) then the problem is solved. This issue can be closed.

**Comment by chotaire** [comment] 2020-01-30 00:46
All snapshot issues fixed in current develop branch, supporting VirtualBox 6.1. This issue can be closed.

**Closed** 2020-01-30 02:32 UTC
